sudo: required
language: generic 
services: 
  - docker

before_install:
  - docker build -t lastsummer/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lastsummer/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-270177653562"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master