sudo: required
language: generic 
services: 
  - docker

before_install:
  - docker build -t lastsummer/docker-react -f Dockerfile.dev .

script:
  - docker run lastsummer/docker-react npm run test -- --coverage